version: '3.8'

services:
  api:
    build: .
    container_name: eternityzone_api
    ports:
      - "7001:7001"
    volumes:
      - ../backend:/app
    command: uvicorn api.main:app --host 0.0.0.0 --port 7001 --reload
